### PR TITLE
 Add Tags to Projects component #16 

### PR DESCRIPTION
**Pull request by AndrewKohn**
**Regarding issue #16.**

ca2b6a06a16e2009a0beaef7f0a5acd7

I created a ProjectTags component, because it may be used elsewhere like in the project's dedicated info page or if more projects gets added.  It's also my first time touching tailwind and I feel like I shouldn't clutter the tailwind.config file, so I kept stylings in the ProjectTags component to keep things together and relevant.  I did add a few tags to get started.

Let me know if there's any changes you'd like me to make.

### CODE REVIEW

**Review by cehicm — APPROVED** [review]

**Review by cehicm — APPROVED** [review]

**Review by cehicm — APPROVED** [review]

**Review by cehicm — CHANGES_REQUESTED** [review]
We might want to reuse these colors, so it would be great if we could add the to the Tailwind config. You can see how to do that [here](https://tailwindcss.com/docs/configuration).

**Comment by cehicm** [comment]
Overall great work, especially considering that it's your first time with Tailwind, just make the changes and we can approve. Thanks!

**Comment by nikolap994** [comment]
Can we add same tags on project page ? 
For example here https://evil-bees-kddpw099p-evil-bees.vercel.app/projects/alertit
Maybe below `Monitoring everything that matters to you.` ?

@cehicm how does this sound to you ?

**Comment by nikolap994** [comment]
@cehicm can you do the review ?

**Review by cehicm — APPROVED** [review]

**Review by cehicm — APPROVED** [review]

**Review by cehicm — APPROVED** [review]

**Review by cehicm — APPROVED** [review]

**Comment by cehicm** [comment]
Great work, thanks @AndrewKohn !

**Pull request merged**
